version: "3.9"
services:
    app:
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
        ports:
            - 80:80
            - 8888:8888
        container_name: news